services:

  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/laravel
    depends_on:
      - app
      - mysql
    networks:
      - webapp

  app:
    build:
      context: dockerfiles
      dockerfile: app.dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./src:/var/www/laravel
    networks:
      - webapp

  mysql:
    image: mysql:8.0.32
    restart: always
    ports:
      - "3316:3306"
    env_file:
      - ./env/mysql.env
    volumes:
      - app_db_data:/var/lib/mysql
    command: --authentication_policy=mysql_native_password
    networks:
      - webapp

networks:
  webapp:

volumes:
  app_db_data:
